### PR TITLE
Fixes crash on `renamed` file change status

### LINKED ISSUE #93: Files rename error
The following error appears when files are renamed:

```
(node:3580) UnhandledPromiseRejectionWarning: Error: {"error":"500/TypeError","from":"sortChangedFiles","message":"There was an issue sorting files changed.","payload":"{}"}
    at run (/home/runner/work/_actions/trilom/file-changes-action/v1.2.3/dist/index.js:1:19989)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]There was an issue sorting changed files from Github.
Exception: {
  "error": "500/TypeError",
  "from": "sortChangedFiles",
  "message": "There was an issue sorting files changed.",
  "payload": "{}"
}
```

Setup looks like this:

```
steps:
  - id: file_changes
    uses: trilom/file-changes-action@v1.2.3
    with:
      output: 'json' # optional output format
  - name: Checkout
    uses: actions/checkout@v2
  - name: Dummy Action
    uses: ./ # Uses an action in the root directory
    id: dummy_action
    with:
      authToken: ${{ secrets.GITHUB_TOKEN }}
      files_added: ${{ steps.file_changes.outputs.files_added }}
      files_modified: ${{ steps.file_changes.outputs.files_modified }}
      files_removed: ${{ steps.file_changes.outputs.files_removed }}
```

**Is there a recommended way to get renamed files?**
(BTW, cool action)

### PR DESCRIPTION
**Pull request by kaineer**
### Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation
- [ ] Refactor
- [ ] Chore

### Resolves
- Fixes #93 

### Describe Changes

Adds an array `changedFiles.renamed` for files that were renamed.
Hopefully it will help.

(May be it should check for old filename also?)

### CODE REVIEW

**Comment by trilom** [comment]
- tyftc

I will review this today.

**Comment by kaineer** [comment]
@trilom Looks I just cannot improve it more. Will you fix the rest?

**Comment by trilom** [comment]
Thank you! 

I can handle from here, appreciate!

**Comment by trilom** [comment]
I haven't cracked open this book in a minute, but I think the integration tests are failing because of how the action is running.

When running from an outside PR it doesn't have a token, so when it runs the integration tests it needs a token to do api requests.  I don't recall if it can use the Action runner token or why it's that way, but it's not you.

**Pull request merged**
