### PR TITLE
#81: Allow single spaces in format

### LINKED ISSUE #81: `output` doesn't work with single space strings
**Describe the bug**
When using the `output` parameter with an empty string, the files are concatenated together without any separator.

**Workflow**
```
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        output: ' '
    - name: Echo file changes
      run: |
        echo Changed files: ${{ steps.get_file_changes.outputs.files }}
```
**Expected behavior**
Files should output with spaces between them, e.g. `file1 file2`. Instead, they are output together: `file1file2`

### PR DESCRIPTION
**Pull request by dorner**
### Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation
- [ ] Refactor
- [ ] Chore

### Resolves
- Fixes #81 

### Describe Changes
Adds a "space" special delimiter value so this works with single spaces (GitHub automatically trims these values before the code gets to them).

### CODE REVIEW

**Comment by trilom** [comment]
Thank you - i'm going to merge this into the `fix-payloads` branch where I am circling around testing regarding this specific issue.  I was still trying to understand where it was being trimmed at - so you're saying if you pass a ' '(single space) to the action as an `output` or `fileOutput` input then the app receives a '' (trimmed space)?

**Comment by dorner** [comment]
Correct - at least from my own experiments. The YAML file has a single space `' '` but `getInput` returns an empty string.

**Comment by trilom** [comment]
Thank you so much for the feedback, and the blog shoutout.  I really appreciate it.  I'll have this fixed and merged soon.

**Comment by dorner** [comment]
Awesome, thanks!

**Pull request merged**
