### PR TITLE
Add ability to output in plaintext

### PR DESCRIPTION
**Pull request by dorner**
This creates the files and outputs in plain text instead of JSON strings. This is helpful for passing into other functions via command line (e.g. linters).

Note that I manually edited the .js files because I couldn't get `tsc` working.

### CODE REVIEW

**Comment by trilom** [comment]
Hey @dorner thank you so much for your contribution.

I love the idea of having this option I'll work on getting it merged.

**Comment by trilom** [comment]
Thank you very much for the contribution.  I am cleaning up the repo and will go over contribution there and that should resolve #3 and provide easier deployment.

**Comment by dorner** [comment]
Wow, that was fast! 😮 great job, will test this out!

**Comment by dorner** [comment]
@trilom this isn't tagged yet so I can't try it out...?

**Pull request merged**
